apiVersion: v1

kind: Service

metadata:

    name: game-of-life-service

spec:

    selector:

        app: game-of-life

    ports:

        - name: http

          port: 80

          targetPort: 5000
