apiVersion: v1

kind: Service

metadata:

    name: game-of-life-service

spec:

    selector:

        app: game-of-life

    ports:

        - name: http
          protocol: TCP
          port: 80
          targetPort: 5000
          nodePort: 32321
    type: NodePort