apiVersion: v1

kind: Secret

metadata:

  name: {SERVICE_ACCOUNT_NAME_HERE}

  annotations:

    kubernetes.io/service-account.name: "{SERVICE_ACCOUNT_NAME_HERE}"

type: kubernetes.io/service-account-token

data:

  extra: YmFyCg==
