apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-of-life-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: "game-of-life-ingress"
          servicePort: 5000
    host: "wordassociationproject.online"