apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-of-life-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: game-of-life-service
              port:
                number: 5000