apiVersion: v1
kind: Service
metadata:
  name: game-of-life-service

spec:
    type: LoadBalancer
    selector:
        name: game-of-life
    ports:
        - name: http
          port: 5000
          targetPort: 5000