name: movie-management-vultr



on: push



jobs:
  test:

    name: Test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code

        uses: actions/checkout@v3

      - name: Set up Python 3.9

        uses: actions/setup-python@v2

        with:

          python-version: 3.9 # Modify python version HERE

      #Task for installing dependencies, multi-line command

      - name: Install dependencies

        run: |
          
          python -m pip install --upgrade pip
          
          python -m pip install black pytest
          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run unit test and integration test

        env:

          DB_HOST: ${{ secrets.DB_HOST }}

          DB_USERNAME: ${{ secrets.DB_USERNAME }}

          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

          DB_PORT: ${{ secrets.DB_PORT }}

          DB_NAME: ${{ secrets.DB_NAME }}

        run: |
          
          echo "Hello World"
  build:

    name: Build

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v1



      - name: Login to GitHub Container Registry

        uses: docker/login-action@v2

        with:

          registry: ghcr.io

          username: ${{github.actor}}

          password: ${{ secrets.GH_TOKEN }}



      - name: Build and push the Docker image

        uses: docker/build-push-action@v3

        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: |

            ghcr.io/arielpro2/game-of-life-multiplayer:latest

            ghcr.io/arielpro2/game-of-life-multiplayer:${{ github.sha }}

          cache-from: type=gha

          cache-to: type=gha,mode=max

  deploy:

    name: Deploy

    needs: [ test, build ]

    runs-on: ubuntu-latest

    steps:

      - name: Set the Kubernetes context

        uses: azure/k8s-set-context@v2

        with:

          method: service-account

          k8s-url: https://45e5b16e-c141-496b-9646-2e3ca5adb996.vultr-k8s.com:6443

          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code

        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster

        uses: azure/k8s-deploy@v1

        with:

          namespace: default

          manifests: |

            kubernetes/deployment.yaml

          images: |

            ghcr.io/arielpro2/game-of-life-multiplayer:${{ github.sha }}